<ul class="trade-five_bets">
  <li>
    <span>卖5</span>
    <span>9.97</span>
    <span>2029</span>
  </li>
  <li>
    <span>卖4</span>
    <span>9.96</span>
    <span>2029</span>
  </li>
  <li>
    <span>卖3</span>
    <span>9.95</span>
    <span>2029</span>
  </li>
  <li>
    <span>卖2</span>
    <span>9.94</span>
    <span>2029</span>
  </li>
  <li>
    <span>卖1</span>
    <span>9.93</span>
    <span>2029</span>
  </li>
</ul>
<ul class="trade-five_bets">
  <li>
    <span>买5</span>
    <span>9.97</span>
    <span>2029</span>
  </li>
  <li>
    <span>买4</span>
    <span>9.96</span>
    <span>2029</span>
  </li>
  <li>
    <span>买3</span>
    <span>9.95</span>
    <span>2029</span>
  </li>
  <li>
    <span>买2</span>
    <span>9.94</span>
    <span>2029</span>
  </li>
  <li>
    <span>买1</span>
    <span>9.93</span>
    <span>2029</span>
  </li>
</ul>